//fichier de scripting où on écrit les commandes de notre pipeline
pipeline{
    agent any
    stages {
        stage ("CONTINUOUS DOWNLOAD"){
            steps{
                git branch: 'main', url: 'https://github.com/ChirazForm2023/Sieli-code.git'
            }
        }
    }
}